version: '3.9'  # Versão compatível com o Compose V2

services:
  pg_tasks:
    container_name: pg-tasks
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    networks:
      mynetwork:
        ipv4_address: 172.30.0.10  # IP fixo atribuído ao container
    ports:
      - "5433:5432"

  sonarqube:
    container_name: sonar
    image: sonarqube:9.9.7-community
    ports:
      - "9000:9000"
    networks:
      mynetwork:
        ipv4_address: 172.30.0.11
    environment:
      - sonar.jdbc.url=jdbc:postgresql://pg-sonar:5434/sonar
    depends_on:
      - pg-sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  pg-sonar:
    container_name: pg-sonar
    image: postgres:latest
    networks:
      mynetwork:
        ipv4_address: 172.30.0.12
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:latest
    container_name: csn-jenkins
    ports:
      - "8010:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
    networks:
      mynetwork:
        ipv4_address: 172.30.0.13

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16  # Sub-rede personalizada
          gateway: 172.30.0.1  # informar este ip de conexao de banco

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  jenkins_home: